/* Formatted on 7/22/2025 6:00:20 PM (QP5 v5.374) */
DROP USER discount_shop CASCADE;
/

CREATE USER discount_shop IDENTIFIED BY a
    ACCOUNT UNLOCK;
/

GRANT DBA TO discount_shop;
/

BEGIN
    FOR t IN (SELECT table_name
                FROM all_tables
               WHERE owner = 'discount_shop')
    LOOP
        BEGIN
            EXECUTE IMMEDIATE   'DROP TABLE discount_shop.'
                             || t.table_name
                             || ' CASCADE CONSTRAINTS';

            DBMS_OUTPUT.PUT_LINE ('Dropped table: ' || t.table_name);
        EXCEPTION
            WHEN OTHERS
            THEN
                IF SQLCODE != -942
                THEN                -- ORA-00942: table or view does not exist
                    DBMS_OUTPUT.PUT_LINE (
                        'Error dropping ' || t.table_name || ': ' || SQLERRM);
                END IF;
        END;
    END LOOP;
END;
/


---------Pagoole-Discount-Shop : Table Started----------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE discount_shop.ALL_OBJECT_HISTORY
(
    ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR2 (64) NOT NULL UNIQUE,
    DESCRIPTION    VARCHAR2 (512),
    ORDER_BY       NUMBER NOT NULL,
    ENTRY_DATE     DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ALL_OBJECT_HISTORY',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE TABLE discount_shop.ALL_ERROR_LOG
(
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ERROR_CODE    NUMBER NOT NULL ENABLE,
    ERROR_MSG     VARCHAR2 (4000) NOT NULL ENABLE,
    APP_ID        NUMBER NOT NULL ENABLE,
    ERROR_TIME    DATE DEFAULT SYSDATE NOT NULL ENABLE,
    USERNAME      VARCHAR2 (64)
                     DEFAULT NVL (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'),
                                  USER)
                     NOT NULL ENABLE,
    PAGE_ID       NUMBER DEFAULT -1 NOT NULL ENABLE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ALL_ERROR_LOG',
           'Stores all database errors',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/


-- USERS TABLE

CREATE TABLE discount_shop.APP_USERS
(
    USERID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USERNAME      VARCHAR2 (100) UNIQUE NOT NULL,
    EMAIL         VARCHAR2 (150) UNIQUE NOT NULL,
    PHONE         VARCHAR2 (20),
    IS_ACTIVE     NUMBER (1) DEFAULT 0 NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.APP_USERS',
           'Stores all users information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE TABLE discount_shop.GEO_LOCATION
(
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NAME            VARCHAR2 (128) NOT NULL,
    FULL_ADDRESS    VARCHAR2 (255),
    PARENT_ID       NUMBER (6, 0) REFERENCES discount_shop.GEO_LOCATION (ID),
    IS_ACTIVE       NUMBER (1, 0) NOT NULL,
    ENTRY_DATE      DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY      NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT GEO_LOCATION_PK PRIMARY KEY (ID) USING INDEX ENABLE,
    CONSTRAINT GEO_LOCATION_CREATED_BY_FK FOREIGN KEY (CREATED_BY)
        REFERENCES discount_shop.APP_USERS (USERID),
    CONSTRAINT GEO_LOCATION_UK UNIQUE (NAME, PARENT_ID)
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.GEO_LOCATION',
           'Stores all locations information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- VENDORS TABLE

CREATE TABLE discount_shop.VENDORS
(
    ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USER_ID              NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    STORE_NAME           VARCHAR2 (150) NOT NULL,
    STORE_DESCRIPTION    VARCHAR2 (500),
    STORE_LOGO           VARCHAR2 (200),
    ADDRESS              VARCHAR2 (300),
    LOCATION_ID          NUMBER
                            NOT NULL
                            REFERENCES discount_shop.GEO_LOCATION (ID),
    IS_ACTIVE            NUMBER (1) DEFAULT 0 NOT NULL,
    CREATED_AT           DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.VENDORS',
           'Stores all sellers information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- CATEGORIES TABLE

CREATE TABLE discount_shop.CATEGORIES
(
    ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME    VARCHAR2 (100) NOT NULL,
    PARENT_ID        NUMBER REFERENCES discount_shop.CATEGORIES (ID),
    ORDER_BY         NUMBER,
    IS_ACTIVE        NUMBER (1) DEFAULT 1 NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.CATEGORIES',
           'Stores all sellers information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE TABLE discount_shop.BRANDS
(
    ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR2 (100) NOT NULL UNIQUE,
    DESCRIPTION    VARCHAR2 (500),
    LOGO_URL       VARCHAR2 (255),
    CREATED_AT     DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.BRANDS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE TABLE discount_shop.WEIGHTS
(
    ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    VALUE          NUMBER (10, 2) NOT NULL,                      -- e.g., 1.00
    UNIT           VARCHAR2 (10) NOT NULL,            -- e.g., 'kg', 'g', 'lb'
    DESCRIPTION    VARCHAR2 (100),                     -- optional description
    CONSTRAINT WEIGHTS_UK UNIQUE (VALUE, UNIT)
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.WEIGHTS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- Store all our servers informations.

CREATE TABLE discount_shop.FILE_SERVER
(
    ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2 (64) NOT NULL UNIQUE,
    BASE_URL      VARCHAR2 (128) NOT NULL UNIQUE,
    CREATED_AT    DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.FILE_SERVER',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- STANDARD PRODUCTS TABLE

CREATE TABLE discount_shop.PRODUCTS
(
    ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME              VARCHAR2 (150) NOT NULL,
    DESCRIPTION       VARCHAR2 (512),
    STANDARD_PRICE    NUMBER (10, 2) NOT NULL,
    SERVER_ID         NUMBER NOT NULL,
    BRAND_ID          NUMBER REFERENCES discount_shop.BRANDS (ID),
    CATEGORY_ID       NUMBER REFERENCES discount_shop.CATEGORIES (ID),
    WEIGHT_ID         NUMBER REFERENCES discount_shop.WEIGHTS (ID),
    CREATED_AT        DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PRODUCT_IMG_SERVER FOREIGN KEY (SERVER_ID)
        REFERENCES discount_shop.FILE_SERVER (ID)
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PRODUCTS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- VENDOR_PRODUCTS TABLE

CREATE TABLE discount_shop.VENDOR_PRODUCTS
(
    ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRODUCT_ID        NUMBER NOT NULL REFERENCES discount_shop.PRODUCTS (ID),
    VENDOR_ID         NUMBER NOT NULL REFERENCES discount_shop.VENDORS (ID),
    PRICE             NUMBER (10, 2) NOT NULL,
    STOCK_QUANTITY    NUMBER DEFAULT 0,
    IMAGE_URL         VARCHAR2 (255),
    IS_ACTIVE         NUMBER (1) DEFAULT 1 NOT NULL,
    CREATED_AT        DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.VENDOR_PRODUCTS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/



CREATE TABLE discount_shop.PRODUCT_IMAGES
(
    ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRODUCT_ID    NUMBER NOT NULL,
    FILE_NAME     VARCHAR2 (64) NOT NULL,
    CONSTRAINT FK_PRODUCT_IMG_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES discount_shop.PRODUCTS (ID)
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PRODUCT_IMAGES',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

ALTER TABLE discount_shop.PRODUCTS
    ADD (IMAGE_ID NUMBER);

ALTER TABLE discount_shop.PRODUCTS
    ADD CONSTRAINT FK_PRODUCTS_IMAGE FOREIGN KEY (IMAGE_ID)
            REFERENCES discount_shop.PRODUCT_IMAGES (ID);
/

-- CARTS TABLE

CREATE TABLE discount_shop.CARTS
(
    ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USER_ID       NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    CREATED_AT    DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.CARTS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- CART ITEMS TABLE (REFERENCES VENDOR_PRODUCTS)

CREATE TABLE discount_shop.CART_ITEMS
(
    ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CART_ID              NUMBER
                            NOT NULL
                            REFERENCES discount_shop.CARTS (ID) ON DELETE CASCADE,
    VENDOR_PRODUCT_ID    NUMBER
                            NOT NULL
                            REFERENCES discount_shop.VENDOR_PRODUCTS (ID),
    QUANTITY             NUMBER DEFAULT 1
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.CART_ITEMS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- ORDERS TABLE

CREATE TABLE discount_shop.ORDERS
(
    ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USER_ID           NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    TOTAL_AMOUNT      NUMBER (10, 2) NOT NULL,
    ORDER_STATUS      VARCHAR2 (20) DEFAULT 'Pending',
    PAYMENT_STATUS    VARCHAR2 (20) DEFAULT 'Unpaid',
    CREATED_AT        DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ORDERS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- ORDER ITEMS TABLE (REFERENCES VENDOR_PRODUCTS)

CREATE TABLE discount_shop.ORDER_ITEMS
(
    ID                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ORDER_ID             NUMBER
                            NOT NULL
                            REFERENCES discount_shop.ORDERS (ID) ON DELETE CASCADE,
    VENDOR_PRODUCT_ID    NUMBER
                            NOT NULL
                            REFERENCES discount_shop.VENDOR_PRODUCTS (ID),
    QUANTITY             NUMBER DEFAULT 1,
    UNIT_PRICE           NUMBER (10, 2) NOT NULL
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ORDER_ITEMS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- PAYMENTS TABLE

CREATE TABLE discount_shop.PAYMENTS
(
    ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ORDER_ID          NUMBER NOT NULL REFERENCES discount_shop.ORDERS (ID),
    PAYMENT_METHOD    VARCHAR2 (50),
    PAYMENT_DATE      DATE DEFAULT SYSDATE,
    AMOUNT            NUMBER (10, 2) NOT NULL,
    STATUS            VARCHAR2 (20) DEFAULT 'Pending'
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PAYMENTS',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- SHIPPING ADDRESSES TABLE

CREATE TABLE discount_shop.SHIPPING_ADDRESSES
(
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    FULL_NAME       VARCHAR2 (100),
    PHONE           VARCHAR2 (20),
    ADDRESS_LINE    VARCHAR2 (300),
    CITY            VARCHAR2 (100),
    POSTAL_CODE     VARCHAR2 (20),
    COUNTRY         VARCHAR2 (100),
    CREATED_AT      DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.SHIPPING_ADDRESSES',
           'Stores all objects information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- REVIEWS TABLE (Linked to STANDARD PRODUCT, not vendor-specific)

CREATE TABLE discount_shop.PRODUCT_REVIEW
(
    ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRODUCT_ID     NUMBER NOT NULL REFERENCES discount_shop.PRODUCTS (ID),
    USER_ID        NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    RATING         NUMBER (1) CHECK (RATING BETWEEN 1 AND 5),
    REMARKS        VARCHAR2 (1000),
    REVIEW_DATE    DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PRODUCT_REVIEW',
           'Stores all product review information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- REVIEWS TABLE (Linked to Sellers / vendor-specific);

CREATE TABLE discount_shop.VENDOR_REVIEW
(
    ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    VENDOR_ID      NUMBER NOT NULL REFERENCES discount_shop.VENDORS (ID),
    USER_ID        NUMBER NOT NULL REFERENCES discount_shop.APP_USERS (USERID),
    RATING         NUMBER (1) CHECK (RATING BETWEEN 1 AND 5),
    REMARKS        VARCHAR2 (1000),
    REVIEW_DATE    DATE DEFAULT SYSDATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.VENDOR_REVIEW',
           'Stores all product review information',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE TABLE discount_shop.ALL_PROCESS_LOG
(
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CHUNK_ID        NUMBER NOT NULL ENABLE,
    MESSAGE         VARCHAR2 (4000),
    PROCESS_TIME    DATE DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT ALL_PROCESS_LOG_PK PRIMARY KEY (ID) USING INDEX ENABLE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ALL_PROCESS_LOG',
           'Stores all process log history.',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/


CREATE TABLE discount_shop.APPLICATION_CONFIGURATION
(
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONFIG_KEY      VARCHAR2 (32) NOT NULL UNIQUE,
    DATA_TYPE     VARCHAR2 (16), -- e.g., 'STRING', 'NUMBER',
    CONFIG_VALUE    VARCHAR2 (4000),
    DESCRIPTION     VARCHAR2 (128),
    STATUS          NUMBER (1) DEFAULT 1,
    CREATED_BY      NUMBER (12),
    CREATED_DATE    DATE DEFAULT SYSDATE,
    UPDATED_BY      NUMBER (12),
    UPDATED_DATE    DATE
);

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.APPLICATION_CONFIGURATION',
           'Stores all configuration values.',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

---------Pagoole-Discount-Shop : Table Ended----------------------------------------------------------------------------------------------------------------------------------------------------------------------














-- INDEXES FOR PERFORMANCE

CREATE INDEX discount_shop.IDX_PRODUCTS_NAME
    ON discount_shop.PRODUCTS (NAME);

CREATE INDEX discount_shop.IDX_VENDOR_PRODUCTS_VENDOR
    ON discount_shop.VENDOR_PRODUCTS (VENDOR_ID);

CREATE INDEX discount_shop.IDX_VENDOR_PRODUCTS_PRODUCT
    ON discount_shop.VENDOR_PRODUCTS (PRODUCT_ID);

CREATE INDEX discount_shop.IDX_ORDERS_USER
    ON discount_shop.ORDERS (USER_ID);

CREATE INDEX discount_shop.IDX_PRODUCT_CATEGORY
    ON discount_shop.PRODUCTS (CATEGORY_ID);
/

CREATE OR REPLACE PROCEDURE discount_shop.ALL_INS_ERROR_LOG (
    p_code      NUMBER,
    p_message   VARCHAR2,
    p_app_id    NUMBER DEFAULT -1,
    p_page_id   NUMBER DEFAULT -1,
    p_user      VARCHAR2 DEFAULT USER)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    l_username   VARCHAR2 (64);
BEGIN
    BEGIN
        IF p_user IS NULL
        THEN
            l_username := SYS_CONTEXT ('APEX$SESSION', 'APP_USER');
        ELSE
            l_username := p_user;
        END IF;
    EXCEPTION
        WHEN OTHERS
        THEN
            l_username := 'Auto';
    END;

    INSERT INTO discount_shop.ALL_ERROR_LOG (ERROR_CODE,
                                             ERROR_MSG,
                                             APP_ID,
                                             PAGE_ID,
                                             USERNAME)
         VALUES (p_code,
                 SUBSTR (p_message, 1, 4000),
                 NVL (SYS_CONTEXT ('APEX$SESSION', 'APP_ID'), p_app_id),
                 p_page_id,
                 NVL (SYS_CONTEXT ('APEX$SESSION', 'APP_USER'), l_username));

    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        raise_application_error (
            -20001,
               'An error was encountered - Procedure Name: '
            || $$plsql_unit
            || ' at Line No : '
            || $$plsql_line
            || ' Error Code : '
            || SQLCODE
            || ' -ERROR- '
            || SQLERRM);
END ALL_INS_ERROR_LOG;

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.ALL_INS_ERROR_LOG',
           'Insert error log data',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

CREATE OR REPLACE PROCEDURE discount_shop.ALL_INS_PROCESS_LOG (
    p_process_serial   IN OUT NUMBER,
    p_chunk_id                NUMBER,
    p_message                 VARCHAR2)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    IF p_process_serial IS NULL
    THEN
        INSERT INTO discount_shop.ALL_PROCESS_LOG (CHUNK_ID, MESSAGE)
                 VALUES (
                            NVL (p_chunk_id,
                                 TO_CHAR (SYSDATE, 'YYMMDDHH24MISS')),
                            p_message);

        p_process_serial := NULL;
    ELSE
        INSERT INTO discount_shop.ALL_PROCESS_LOG (ID, CHUNK_ID, MESSAGE)
             VALUES (p_process_serial, p_chunk_id, p_message);

        p_process_serial := p_process_serial + 1;
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        discount_shop.ALL_INS_ERROR_LOG (
            p_code      => SQLCODE,
            p_message   =>
                   'An error was encountered - Procedure Name: '
                || $$plsql_unit
                || ' at Line No : '
                || $$plsql_line
                || ' Error Code : '
                || SQLCODE
                || ' -ERROR- '
                || SQLERRM,
            p_app_id    => -2,
            p_page_id   => -2,
            p_user      => USER);
END ALL_INS_PROCESS_LOG;


INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PROC_PROCESS_LOG',
           'Insert process log data',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- Insert Default Value using a default value procedure.

CREATE OR REPLACE PROCEDURE discount_shop.PROC_SET_DEFAULT_VALUE
IS
    vParentId   NUMBER;
    vChuncId    NUMBER := TO_NUMBER (TO_CHAR (SYSDATE, 'YYYYMMDDHH24MISS'));
BEGIN
    -- Step 1: Delete existing data

    -- Delete existing record with USERID = 0
    DELETE FROM discount_shop.APP_USERS
          WHERE USERID = 0;

    -- Insert new record with USERID = 0
    INSERT INTO discount_shop.APP_USERS (USERID,
                                         USERNAME,
                                         EMAIL,
                                         PHONE,
                                         IS_ACTIVE,
                                         CREATED_AT)
         VALUES (0,
                 '0',
                 '0',
                 '0',
                 0,
                 SYSDATE);

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted 1 user as default User with id 0.');

    -- Step 2: Delete existing data
    DELETE FROM discount_shop.WEIGHTS;

    -- Step 3: Insert data with manual ID values
    INSERT INTO discount_shop.WEIGHTS (ID,
                                       VALUE,
                                       UNIT,
                                       DESCRIPTION)
        SELECT 1, 0.1, 'kg', '100 grams' FROM DUAL
        UNION ALL
        SELECT 2, 0.2, 'kg', '200 grams' FROM DUAL
        UNION ALL
        SELECT 3, 0.5, 'kg', '500 grams' FROM DUAL
        UNION ALL
        SELECT 4, 1.0, 'kg', '1 kilogram' FROM DUAL
        UNION ALL
        SELECT 5, 2.0, 'kg', '2 kilograms' FROM DUAL
        UNION ALL
        SELECT 6, 3.0, 'kg', '3 kilograms' FROM DUAL
        UNION ALL
        SELECT 7, 4.0, 'kg', '4 kilograms' FROM DUAL
        UNION ALL
        SELECT 8, 5.0, 'kg', '5 kilograms' FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted default Weight data.');

    -- Commit the changes

    DELETE FROM discount_shop.GEO_LOCATION;

    -- Insert Divisions
    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 1, 'World Wide', NULL, 1, 0 FROM DUAL;

    -- World wilde location id.
    vParentId := 1;
    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted World Wide');

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 2, 'Asia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 3, 'Africa', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 4, 'North America', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 5, 'South America', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 6, 'Europe', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 7, 'Oceania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 8, 'Antarctica', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted 7 continents name.');


    -- Insert Country names of Asia.
    -- Asia location id.

    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Asia';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 200, 'Afghanistan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 201, 'Bangladesh', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 202, 'China', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 203, 'India', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 204, 'Indonesia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 205, 'Iran', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 206, 'Iraq', vParentId, 1, 0 FROM DUAL
        UNION ALL
        --SELECT 207, 'Israel', vParentId, 1, 0 FROM DUAL
        --UNION ALL
        SELECT 208, 'Japan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 209, 'Jordan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 210, 'Kazakhstan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 211, 'Kuwait', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 212, 'Kyrgyzstan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 213, 'Laos', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 214, 'Lebanon', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 215, 'Malaysia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 216, 'Maldives', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 217, 'Mongolia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 218, 'Myanmar', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 219, 'Nepal', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 220, 'North Korea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 221, 'Oman', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 222, 'Pakistan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 223, 'Palestine', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 224, 'Philippines', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 225, 'Qatar', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 226, 'Saudi Arabia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 227, 'Singapore', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 228, 'South Korea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 229, 'Sri Lanka', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 230, 'Syria', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 231, 'Tajikistan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 232, 'Thailand', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 233, 'Timor-Leste', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 234, 'Turkey', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 235, 'Turkmenistan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 236, 'UAE', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 237, 'Uzbekistan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 238, 'Vietnam', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 239, 'Yemen', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of Asia continent.');

    -- Insert Country names of Africa.
    -- Africa location id.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Africa';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 300, 'Algeria', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 301, 'Angola', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 302, 'Benin', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 303, 'Botswana', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 304, 'Burkina Faso', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 305, 'Burundi', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 306, 'Cameroon', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 307, 'Cape Verde', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 308, 'Central African Republic', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 309, 'Chad', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 310, 'Comoros', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 311, 'Congo (Brazzaville)', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 312, 'Congo (Kinshasa)', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 313, 'Djibouti', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 314, 'Egypt', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 315, 'Equatorial Guinea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 316, 'Eritrea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 317, 'Eswatini', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 318, 'Ethiopia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 319, 'Gabon', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 320, 'Gambia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 321, 'Ghana', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 322, 'Guinea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 323, 'Guinea-Bissau', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 324, 'Ivory Coast', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 325, 'Kenya', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 326, 'Lesotho', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 327, 'Liberia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 328, 'Libya', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 329, 'Madagascar', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 330, 'Malawi', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 331, 'Mali', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 332, 'Mauritania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 333, 'Mauritius', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 334, 'Morocco', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 335, 'Mozambique', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 336, 'Namibia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 337, 'Niger', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 338, 'Nigeria', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 339, 'Rwanda', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 340, 'Sao Tome and Principe', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 341, 'Senegal', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 342, 'Seychelles', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 343, 'Sierra Leone', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 344, 'Somalia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 345, 'South Africa', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 346, 'South Sudan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 347, 'Sudan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 348, 'Tanzania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 349, 'Togo', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 350, 'Tunisia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 351, 'Uganda', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 352, 'Zambia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 353, 'Zimbabwe', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of Africa continent.');

    -- Insert Country names of North America.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'North America';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 400, 'Antigua and Barbuda', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 401, 'Bahamas', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 402, 'Barbados', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 403, 'Belize', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 404, 'Canada', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 405, 'Costa Rica', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 406, 'Cuba', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 407, 'Dominica', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 408, 'Dominican Republic', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 409, 'El Salvador', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 410, 'Grenada', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 411, 'Guatemala', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 412, 'Haiti', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 413, 'Honduras', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 414, 'Jamaica', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 415, 'Mexico', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 416, 'Nicaragua', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 417, 'Panama', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 418, 'Saint Kitts and Nevis', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 419, 'Saint Lucia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 420,
               'Saint Vincent and the Grenadines',
               vParentId,
               1,
               0
          FROM DUAL
        UNION ALL
        SELECT 421, 'Trinidad and Tobago', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 422, 'United States', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of North America continent.');


    -- Insert Country names of South America.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'South America';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 501, 'Argentina', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 502, 'Bolivia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 503, 'Brazil', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 504, 'Chile', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 505, 'Colombia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 506, 'Ecuador', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 507, 'Guyana', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 508, 'Paraguay', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 509, 'Peru', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 510, 'Suriname', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 511, 'Uruguay', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 512, 'Venezuela', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of South America continent.');

    -- Insert Country names of Europe.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Europe';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 601, 'Albania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 602, 'Andorra', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 603, 'Armenia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 604, 'Austria', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 605, 'Azerbaijan', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 606, 'Belarus', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 607, 'Belgium', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 608, 'Bosnia and Herzegovina', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 609, 'Bulgaria', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 610, 'Croatia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 611, 'Cyprus', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 612, 'Czech Republic', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 613, 'Denmark', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 614, 'Estonia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 615, 'Finland', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 616, 'France', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 617, 'Georgia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 618, 'Germany', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 619, 'Greece', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 620, 'Hungary', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1149, 'Iceland', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1150, 'Ireland', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1151, 'Italy', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1152, 'Latvia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1153, 'Liechtenstein', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1154, 'Lithuania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1155, 'Luxembourg', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1156, 'Malta', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1157, 'Moldova', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1158, 'Monaco', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1159, 'Montenegro', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1160, 'Netherlands', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1161, 'North Macedonia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1162, 'Norway', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1163, 'Poland', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1164, 'Portugal', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1165, 'Romania', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1166, 'Russia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1167, 'San Marino', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1168, 'Serbia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1169, 'Slovakia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1170, 'Slovenia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1171, 'Spain', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1172, 'Sweden', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1173, 'Switzerland', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1174, 'Ukraine', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1175, 'United Kingdom', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1176, 'Vatican City', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of Europe continent.');

    -- Insert Country names of Oceania.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Oceania';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 1177, 'Australia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1178, 'Fiji', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1179, 'Kiribati', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1180, 'Marshall Islands', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1181, 'Micronesia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1182, 'Nauru', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1183, 'New Zealand', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1184, 'Palau', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1185, 'Papua New Guinea', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1186, 'Samoa', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1187, 'Solomon Islands', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1188, 'Tonga', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1189, 'Tuvalu', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 1190, 'Vanuatu', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of Oceania continent.');

    -- Insert Country names of Antarctica.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Antarctica';

    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE,
                                            CREATED_BY)
        SELECT 801, 'Argentina', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 802, 'Australia', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 803, 'Chile', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 804, 'France', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 805, 'New Zealand', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 806, 'Norway', vParentId, 1, 0 FROM DUAL
        UNION ALL
        SELECT 807, 'United Kingdom', vParentId, 1, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          => 'Inserted countries of Antarctica continent.');


    -- Insert Country names of Antarctica.
    SELECT ID
      INTO vParentId
      FROM discount_shop.GEO_LOCATION
     WHERE NAME = 'Bangladesh';

    -- Insert Cities (Dhaka and Chattogram)
    INSERT INTO discount_shop.GEO_LOCATION (ID,
                                            NAME,
                                            PARENT_ID,
                                            IS_ACTIVE)
        SELECT 2011, 'Dhaka', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2012, 'Chattogram', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2013, 'Rajshahi', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2014, 'Khulna', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2015, 'Barisal', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2016, 'Sylhet', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2017, 'Rangpur', vParentId, 0 FROM DUAL
        UNION ALL
        SELECT 2018, 'Mymensingh', vParentId, 0 FROM DUAL;

    discount_shop.ALL_INS_PROCESS_LOG (
        p_process_serial   => vChuncId,
        p_chunk_id         => vChuncId,
        p_message          =>
            'Inserted cities of the country Bangladesh.');

    /*UNION ALL
    -- Dhaka Division
    SELECT 101, 'Dhaka District', 1, 1, 0 FROM DUAL
    UNION ALL
    SELECT 102, 'Gazipur', 1, 1, 0 FROM DUAL
    UNION ALL
    SELECT 103, 'Narayanganj', 1, 1, 0 FROM DUAL
    UNION ALL
    -- Chattogram Division
    SELECT 201, 'Chattogram District', 2, 1, 0 FROM DUAL
    UNION ALL
    SELECT 202, 'Cox’s Bazar', 2, 1, 0 FROM DUAL
    UNION ALL
    SELECT 203, 'Cumilla', 2, 1, 0 FROM DUAL
    UNION ALL
    -- Rajshahi Division
    SELECT 301, 'Rajshahi District', 3, 1, 0 FROM DUAL
    UNION ALL
    SELECT 302, 'Bogra', 3, 1, 0 FROM DUAL
    UNION ALL
    -- Khulna Division
    SELECT 401, 'Khulna District', 4, 1, 0 FROM DUAL
    UNION ALL
    SELECT 402, 'Jessore', 4, 1, 0 FROM DUAL;

INSERT INTO discount_shop.GEO_LOCATION (ID,
                                        NAME,
                                        PARENT_ID,
                                        IS_ACTIVE,
                                        CREATED_BY)
    -- Upazilas under Gazipur
    SELECT 1001, 'Gazipur Sadar', 102, 1, 0 FROM DUAL
    UNION ALL
    SELECT 1002, 'Kaliakair', 102, 1, 0 FROM DUAL
    UNION ALL
    SELECT 1003, 'Sreepur', 102, 1, 0 FROM DUAL
    UNION ALL
    -- Upazilas under Dhaka District
    SELECT 1101, 'Savar', 101, 1, 0 FROM DUAL
    UNION ALL
    SELECT 1102, 'Dhamrai', 101, 1, 0 FROM DUAL
    UNION ALL
    -- Upazilas under Narayanganj
    SELECT 1201, 'Sonargaon', 103, 1, 0 FROM DUAL
    UNION ALL
    SELECT 1202, 'Rupganj', 103, 1, 0 FROM DUAL
    UNION ALL
    -- Upazilas under Cox’s Bazar
    SELECT 2201, 'Ukhia', 202, 1, 0 FROM DUAL
    UNION ALL
    SELECT 2202, 'Teknaf', 202, 1, 0 FROM DUAL
    UNION ALL
    -- Upazilas under Jessore
    SELECT 4201, 'Jhikargacha', 402, 1, 0 FROM DUAL
    UNION ALL
    SELECT 4202, 'Sharsha', 402, 1, 0 FROM DUAL;*/


    COMMIT;
EXCEPTION
    WHEN OTHERS
    THEN
        ROLLBACK;
        discount_shop.ALL_INS_ERROR_LOG (
            p_code      => SQLCODE,
            p_message   =>
                   'An error was encountered - Procedure Name: '
                || $$plsql_unit
                || ' at Line No : '
                || $$plsql_line
                || ' Error Code : '
                || SQLCODE
                || ' -ERROR- '
                || SQLERRM,
            p_app_id    => -2,
            p_page_id   => -2,
            p_user      => 'DatabaseInitializationScript');
        DBMS_OUTPUT.PUT_LINE (
            'ERROR CODE: ' || SQLCODE || ' || ERROR MESSAGE: ' || SQLERRM);
END;

INSERT INTO discount_shop.ALL_OBJECT_HISTORY (ID,
                                              NAME,
                                              DESCRIPTION,
                                              ORDER_BY)
    SELECT NVL (MAX (ID), 0) + 1,
           'discount_shop.PROC_SET_DEFAULT_VALUE',
           'Insert application default values. All types of default value will be inserted using this procedure. The procedure will be modified time to time for all others insertions.',
           NVL (MAX (ORDER_BY), 0) + 1
      FROM discount_shop.ALL_OBJECT_HISTORY;

COMMIT;
/

-- Call the default value set procedure 

BEGIN
    discount_shop.PROC_SET_DEFAULT_VALUE;
END;
/
