import { AlertProvider } from '@/context/AlertContext';
import { DialogProvider } from '@/context/DialogContext';
import Alert from '@components/Alert';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata = {
    title: 'Pagoole.com',
    description: 'Generated by create next js'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <DialogProvider>
                    <AlertProvider>
                        <Alert />
                        {children}
                    </AlertProvider>
                </DialogProvider>
            </body>
        </html>
    );
}
