
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(0, 'Worldwide', 'Worldwide', NULL, 0, NOW(), NULL, NOW(), NOW()),
(1, 'World Wide', 'World Wide >', NULL, 1, NOW(), NULL, NOW(), NOW());

-- Level 1: Children of 'Worldwide' and 'World Wide'
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(2, 'Asia ', 'Test Remarks', 1, 1, NOW(), NULL, NOW(), NOW()),
(3, 'Africa', 'World Wide > Africa >', 1, 1, NOW(), NULL, NOW(), NOW()),
(4, 'North America', 'World Wide > North America >', 1, 1, NOW(), NULL, NOW(), NOW()),
(5, 'South America', 'World Wide > South America >', 1, 1, NOW(), NULL, NOW(), NOW()),
(6, 'Antarctica', 'World Wide > Antarctica >', 1, 1, NOW(), NULL, NOW(), NOW()),
(7, 'Europe', 'World Wide > Europe >', 1, 1, NOW(), NULL, NOW(), NOW()),
(8, 'Australia', 'World Wide > Australia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(384, 'Fiji', 'World Wide > Fiji >', 1, 1, NOW(), NULL, NOW(), NOW()),
(402, 'Vanuatu', 'World Wide > Vanuatu >', 1, 1, NOW(), NULL, NOW(), NOW()),
(403, 'Afghanistan', 'World Wide > Afghanistan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(404, 'Namibia', 'World Wide > Namibia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(421, 'Indonesia', 'World Wide > Indonesia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(422, 'Albania', 'World Wide > Albania >', 1, 1, NOW(), NULL, NOW(), NOW()),
(423, 'Uganda', 'World Wide > Uganda >', 1, 1, NOW(), NULL, NOW(), NOW()),
(441, 'Bahamas', 'World Wide > Bahamas >', 1, 1, NOW(), NULL, NOW(), NOW()),
(461, 'British Virgin Islands', 'World Wide > British Virgin Islands >', 1, 1, NOW(), NULL, NOW(), NOW()),
(481, 'Taiwan', 'World Wide > Taiwan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(501, 'Nicaragua', 'World Wide > Nicaragua >', 1, 1, NOW(), NULL, NOW(), NOW()),
(521, 'Barbados', 'World Wide > Barbados >', 1, 1, NOW(), NULL, NOW(), NOW()),
(541, 'Macau', 'World Wide > Macau >', 1, 1, NOW(), NULL, NOW(), NOW()),
(561, 'CTG', 'World Wide > CTG >', 1, 1, NOW(), NULL, NOW(), NOW()),
(581, 'Mymenshing', 'World Wide > Mymenshing >', 1, 1, NOW(), NULL, NOW(), NOW()),
(601, 'New Zealand', 'World Wide > New Zealand >', 1, 1, NOW(), NULL, NOW(), NOW()),
(641, 'Algeria', 'Algeria >', 1, 1, NOW(), NULL, NOW(), NOW()),
(642, 'Angola', 'Angola >', 1, 1, NOW(), NULL, NOW(), NOW()),
(643, 'Benin', 'Benin >', 1, 1, NOW(), NULL, NOW(), NOW()),
(644, 'Botswana', 'Botswana >', 1, 1, NOW(), NULL, NOW(), NOW()),
(645, 'Burkina', 'Burkina >', 1, 1, NOW(), NULL, NOW(), NOW()),
(646, 'Burundi', 'Burundi >', 1, 1, NOW(), NULL, NOW(), NOW()),
(647, 'Cameroon', 'Cameroon >', 1, 1, NOW(), NULL, NOW(), NOW()),
(648, 'Cape Verde', 'Cape Verde >', 1, 1, NOW(), NULL, NOW(), NOW()),
(649, 'Central African Republic', 'Central African Republic >', 1, 1, NOW(), NULL, NOW(), NOW()),
(650, 'Chad', 'Chad >', 1, 1, NOW(), NULL, NOW(), NOW()),
(651, 'Comoros', 'Comoros >', 1, 1, NOW(), NULL, NOW(), NOW()),
(652, 'Congo', 'Congo >', 1, 1, NOW(), NULL, NOW(), NOW()),
(653, 'Congo, Democratic Republic of', 'Congo, Democratic Republic of >', 1, 1, NOW(), NULL, NOW(), NOW()),
(654, 'Djibouti', 'Djibouti >', 1, 1, NOW(), NULL, NOW(), NOW()),
(655, 'Egypt', 'Egypt >', 1, 1, NOW(), NULL, NOW(), NOW()),
(656, 'Equatorial Guinea', 'Equatorial Guinea >', 1, 1, NOW(), NULL, NOW(), NOW()),
(657, 'Eritrea', 'Eritrea >', 1, 1, NOW(), NULL, NOW(), NOW()),
(658, 'Ethiopia', 'Ethiopia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(659, 'Gabon', 'Gabon >', 1, 1, NOW(), NULL, NOW(), NOW()),
(660, 'Gambia', 'Gambia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(661, 'Ghana', 'Ghana >', 1, 1, NOW(), NULL, NOW(), NOW()),
(662, 'Guinea', 'Guinea >', 1, 1, NOW(), NULL, NOW(), NOW()),
(663, 'Guinea-Bissau', 'Guinea-Bissau >', 1, 1, NOW(), NULL, NOW(), NOW()),
(664, 'Ivory Coast', 'Ivory Coast >', 1, 1, NOW(), NULL, NOW(), NOW()),
(665, 'Kenya', 'Kenya >', 1, 1, NOW(), NULL, NOW(), NOW()),
(666, 'Lesotho', 'Lesotho >', 1, 1, NOW(), NULL, NOW(), NOW()),
(667, 'Liberia', 'Liberia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(668, 'Libya', 'Libya >', 1, 1, NOW(), NULL, NOW(), NOW()),
(669, 'Madagascar', 'Madagascar >', 1, 1, NOW(), NULL, NOW(), NOW()),
(670, 'Malawi', 'Malawi >', 1, 1, NOW(), NULL, NOW(), NOW()),
(671, 'Mali', 'Mali >', 1, 1, NOW(), NULL, NOW(), NOW()),
(672, 'Mauritania', 'Mauritania >', 1, 1, NOW(), NULL, NOW(), NOW()),
(673, 'Mauritius', 'Mauritius >', 1, 1, NOW(), NULL, NOW(), NOW()),
(674, 'Morocco', 'Morocco >', 1, 1, NOW(), NULL, NOW(), NOW()),
(675, 'Mozambique', 'Mozambique >', 1, 1, NOW(), NULL, NOW(), NOW()),
(676, 'Niger', 'Niger >', 1, 1, NOW(), NULL, NOW(), NOW()),
(677, 'Nigeria', 'Nigeria >', 1, 1, NOW(), NULL, NOW(), NOW()),
(678, 'Rwanda', 'Rwanda >', 1, 1, NOW(), NULL, NOW(), NOW()),
(679, 'Sao Tome and Principe', 'Sao Tome and Principe >', 1, 1, NOW(), NULL, NOW(), NOW()),
(680, 'Senegal', 'Senegal >', 1, 1, NOW(), NULL, NOW(), NOW()),
(681, 'Seychelles', 'Seychelles >', 1, 1, NOW(), NULL, NOW(), NOW()),
(682, 'Sierra Leone', 'Sierra Leone >', 1, 1, NOW(), NULL, NOW(), NOW()),
(683, 'Somalia', 'Somalia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(684, 'South Africa', 'South Africa >', 1, 1, NOW(), NULL, NOW(), NOW()),
(685, 'South Sudan', 'South Sudan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(686, 'Sudan', 'Sudan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(687, 'Swaziland', 'Swaziland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(688, 'Tanzania', 'Tanzania >', 1, 1, NOW(), NULL, NOW(), NOW()),
(689, 'Togo', 'Togo >', 1, 1, NOW(), NULL, NOW(), NOW()),
(690, 'Tunisia', 'Tunisia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(691, 'Zambia', 'Zambia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(692, 'Zimbabwe', 'Zimbabwe >', 1, 1, NOW(), NULL, NOW(), NOW()),
(693, 'Bahrain', 'Bahrain >', 1, 1, NOW(), NULL, NOW(), NOW()),
(694, 'Bhutan', 'Bhutan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(695, 'Brunei', 'Brunei >', 1, 1, NOW(), NULL, NOW(), NOW()),
(696, 'Burma (Myanmar)', 'Burma (Myanmar) >', 1, 1, NOW(), NULL, NOW(), NOW()),
(697, 'Cambodia', 'Cambodia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(698, 'China', 'China >', 1, 1, NOW(), NULL, NOW(), NOW()),
(699, 'East Timor', 'East Timor >', 1, 1, NOW(), NULL, NOW(), NOW()),
(700, 'Iran', 'Iran >', 1, 1, NOW(), NULL, NOW(), NOW()),
(701, 'Iraq', 'Iraq >', 1, 1, NOW(), NULL, NOW(), NOW()),
(702, 'Israel', 'Israel >', 1, 1, NOW(), NULL, NOW(), NOW()),
(703, 'Jordan', 'Jordan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(704, 'Kazakhstan', 'Kazakhstan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(705, 'Korea, North', 'Korea, North >', 1, 1, NOW(), NULL, NOW(), NOW()),
(706, 'Korea, South', 'Korea, South >', 1, 1, NOW(), NULL, NOW(), NOW()),
(707, 'Kuwait', 'Kuwait >', 1, 1, NOW(), NULL, NOW(), NOW()),
(708, 'Kyrgyzstan', 'Kyrgyzstan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(709, 'Laos', 'Laos >', 1, 1, NOW(), NULL, NOW(), NOW()),
(710, 'Lebanon', 'Lebanon >', 1, 1, NOW(), NULL, NOW(), NOW()),
(711, 'Malaysia', 'Malaysia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(712, 'Maldives', 'Maldives >', 1, 1, NOW(), NULL, NOW(), NOW()),
(713, 'Mongolia', 'Mongolia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(714, 'Nepal', 'Nepal >', 1, 1, NOW(), NULL, NOW(), NOW()),
(715, 'Oman', 'Oman >', 1, 1, NOW(), NULL, NOW(), NOW()),
(716, 'Pakistan', 'Pakistan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(717, 'Philippines', 'Philippines >', 1, 1, NOW(), NULL, NOW(), NOW()),
(718, 'Qatar', 'Qatar >', 1, 1, NOW(), NULL, NOW(), NOW()),
(719, 'Russian Federation', 'Russian Federation >', 1, 1, NOW(), NULL, NOW(), NOW()),
(720, 'Saudi Arabia', 'Saudi Arabia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(721, 'Singapore', 'Singapore >', 1, 1, NOW(), NULL, NOW(), NOW()),
(722, 'Sri Lanka', 'Sri Lanka >', 1, 1, NOW(), NULL, NOW(), NOW()),
(723, 'Syria', 'Syria >', 1, 1, NOW(), NULL, NOW(), NOW()),
(724, 'Tajikistan', 'Tajikistan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(725, 'Thailand', 'Thailand >', 1, 1, NOW(), NULL, NOW(), NOW()),
(726, 'Turkey', 'Turkey >', 1, 1, NOW(), NULL, NOW(), NOW()),
(727, 'Turkmenistan', 'Turkmenistan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(728, 'United Arab Emirates', 'United Arab Emirates >', 1, 1, NOW(), NULL, NOW(), NOW()),
(729, 'Uzbekistan', 'Uzbekistan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(730, 'Vietnam', 'Vietnam >', 1, 1, NOW(), NULL, NOW(), NOW()),
(731, 'Yemen', 'Yemen >', 1, 1, NOW(), NULL, NOW(), NOW()),
(732, 'Andorra', 'Andorra >', 1, 1, NOW(), NULL, NOW(), NOW()),
(733, 'Armenia', 'Armenia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(734, 'Austria', 'Austria >', 1, 1, NOW(), NULL, NOW(), NOW()),
(735, 'Azerbaijan', 'Azerbaijan >', 1, 1, NOW(), NULL, NOW(), NOW()),
(736, 'Belarus', 'Belarus >', 1, 1, NOW(), NULL, NOW(), NOW()),
(737, 'Belgium', 'Belgium >', 1, 1, NOW(), NULL, NOW(), NOW()),
(738, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina >', 1, 1, NOW(), NULL, NOW(), NOW()),
(739, 'Bulgaria', 'Bulgaria >', 1, 1, NOW(), NULL, NOW(), NOW()),
(740, 'Croatia', 'Croatia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(741, 'Cyprus', 'Cyprus >', 1, 1, NOW(), NULL, NOW(), NOW()),
(742, 'CZ', 'CZ >', 1, 1, NOW(), NULL, NOW(), NOW()),
(743, 'Denmark', 'Denmark >', 1, 1, NOW(), NULL, NOW(), NOW()),
(744, 'Estonia', 'Estonia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(745, 'Finland', 'Finland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(746, 'France', 'France >', 1, 1, NOW(), NULL, NOW(), NOW()),
(747, 'Georgia', 'Georgia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(748, 'Germany', 'Germany >', 1, 1, NOW(), NULL, NOW(), NOW()),
(749, 'Greece', 'Greece >', 1, 1, NOW(), NULL, NOW(), NOW()),
(750, 'Hungary', 'Hungary >', 1, 1, NOW(), NULL, NOW(), NOW()),
(751, 'Iceland', 'Iceland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(752, 'Ireland', 'Ireland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(753, 'Italy', 'Italy >', 1, 1, NOW(), NULL, NOW(), NOW()),
(754, 'Latvia', 'Latvia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(755, 'Liechtenstein', 'Liechtenstein >', 1, 1, NOW(), NULL, NOW(), NOW()),
(756, 'Lithuania', 'Lithuania >', 1, 1, NOW(), NULL, NOW(), NOW()),
(757, 'Luxembourg', 'Luxembourg >', 1, 1, NOW(), NULL, NOW(), NOW()),
(758, 'Macedonia', 'Macedonia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(759, 'Malta', 'Malta >', 1, 1, NOW(), NULL, NOW(), NOW()),
(760, 'Moldova', 'Moldova >', 1, 1, NOW(), NULL, NOW(), NOW()),
(761, 'Monaco', 'Monaco >', 1, 1, NOW(), NULL, NOW(), NOW()),
(762, 'Montenegro', 'Montenegro >', 1, 1, NOW(), NULL, NOW(), NOW()),
(763, 'Netherlands', 'Netherlands >', 1, 1, NOW(), NULL, NOW(), NOW()),
(764, 'Norway', 'Norway >', 1, 1, NOW(), NULL, NOW(), NOW()),
(765, 'Poland', 'Poland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(766, 'Portugal', 'Portugal >', 1, 1, NOW(), NULL, NOW(), NOW()),
(767, 'Romania', 'Romania >', 1, 1, NOW(), NULL, NOW(), NOW()),
(768, 'San Marino', 'San Marino >', 1, 1, NOW(), NULL, NOW(), NOW()),
(769, 'Serbia', 'Serbia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(770, 'Slovakia', 'Slovakia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(771, 'Slovenia', 'Slovenia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(772, 'Spain', 'Spain >', 1, 1, NOW(), NULL, NOW(), NOW()),
(773, 'Sweden', 'Sweden >', 1, 1, NOW(), NULL, NOW(), NOW()),
(774, 'Switzerland', 'Switzerland >', 1, 1, NOW(), NULL, NOW(), NOW()),
(775, 'Ukraine', 'Ukraine >', 1, 1, NOW(), NULL, NOW(), NOW()),
(776, 'United Kingdom', 'United Kingdom >', 1, 1, NOW(), NULL, NOW(), NOW()),
(777, 'Vatican City', 'Vatican City >', 1, 1, NOW(), NULL, NOW(), NOW()),
(778, 'Antigua and Barbuda', 'Antigua and Barbuda >', 1, 1, NOW(), NULL, NOW(), NOW()),
(779, 'Belize', 'Belize >', 1, 1, NOW(), NULL, NOW(), NOW()),
(780, 'Costa Rica', 'Costa Rica >', 1, 1, NOW(), NULL, NOW(), NOW()),
(781, 'Cuba', 'Cuba >', 1, 1, NOW(), NULL, NOW(), NOW()),
(782, 'Dominica', 'Dominica >', 1, 1, NOW(), NULL, NOW(), NOW()),
(783, 'Dominican Republic', 'Dominican Republic >', 1, 1, NOW(), NULL, NOW(), NOW()),
(784, 'El Salvador', 'El Salvador >', 1, 1, NOW(), NULL, NOW(), NOW()),
(785, 'Grenada', 'Grenada >', 1, 1, NOW(), NULL, NOW(), NOW()),
(786, 'Guatemala', 'Guatemala >', 1, 1, NOW(), NULL, NOW(), NOW()),
(787, 'Haiti', 'Haiti >', 1, 1, NOW(), NULL, NOW(), NOW()),
(788, 'Honduras', 'Honduras >', 1, 1, NOW(), NULL, NOW(), NOW()),
(789, 'Jamaica', 'Jamaica >', 1, 1, NOW(), NULL, NOW(), NOW()),
(790, 'Mexico', 'Mexico >', 1, 1, NOW(), NULL, NOW(), NOW()),
(791, 'Panama', 'Panama >', 1, 1, NOW(), NULL, NOW(), NOW()),
(792, 'Saint Kitts and Nevis', 'Saint Kitts and Nevis >', 1, 1, NOW(), NULL, NOW(), NOW()),
(793, 'Saint Lucia', 'Saint Lucia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(794, 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines >', 1, 1, NOW(), NULL, NOW(), NOW()),
(795, 'Trinidad and Tobago', 'Trinidad and Tobago >', 1, 1, NOW(), NULL, NOW(), NOW()),
(796, 'US', 'US >', 1, 1, NOW(), NULL, NOW(), NOW()),
(797, 'Kiribati', 'Kiribati >', 1, 1, NOW(), NULL, NOW(), NOW()),
(798, 'Marshall Islands', 'Marshall Islands >', 1, 1, NOW(), NULL, NOW(), NOW()),
(799, 'Micronesia', 'Micronesia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(800, 'Nauru', 'Nauru >', 1, 1, NOW(), NULL, NOW(), NOW()),
(801, 'Palau', 'Palau >', 1, 1, NOW(), NULL, NOW(), NOW()),
(802, 'Papua New Guinea', 'Papua New Guinea >', 1, 1, NOW(), NULL, NOW(), NOW()),
(803, 'Samoa', 'Samoa >', 1, 1, NOW(), NULL, NOW(), NOW()),
(804, 'Solomon Islands', 'Solomon Islands >', 1, 1, NOW(), NULL, NOW(), NOW()),
(805, 'Tonga', 'Tonga >', 1, 1, NOW(), NULL, NOW(), NOW()),
(806, 'Tuvalu', 'Tuvalu >', 1, 1, NOW(), NULL, NOW(), NOW()),
(807, 'Argentina', 'Argentina >', 1, 1, NOW(), NULL, NOW(), NOW()),
(808, 'Bolivia', 'Bolivia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(809, 'Brazil', 'Brazil >', 1, 1, NOW(), NULL, NOW(), NOW()),
(810, 'Chile', 'Chile >', 1, 1, NOW(), NULL, NOW(), NOW()),
(811, 'Colombia', 'Colombia >', 1, 1, NOW(), NULL, NOW(), NOW()),
(812, 'Ecuador', 'Ecuador >', 1, 1, NOW(), NULL, NOW(), NOW()),
(813, 'Guyana', 'Guyana >', 1, 1, NOW(), NULL, NOW(), NOW()),
(814, 'Paraguay', 'Paraguay >', 1, 1, NOW(), NULL, NOW(), NOW()),
(815, 'Peru', 'Peru >', 1, 1, NOW(), NULL, NOW(), NOW()),
(816, 'Suriname', 'Suriname >', 1, 1, NOW(), NULL, NOW(), NOW()),
(817, 'Uruguay', 'Uruguay >', 1, 1, NOW(), NULL, NOW(), NOW()),
(818, 'Venezuela', 'Venezuela >', 1, 1, NOW(), NULL, NOW(), NOW());

-- Level 2: Children of Level 1 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(21, 'Bangladesh', 'World Wide > Asia  > Bangladesh >', 2, 1, NOW(), NULL, NOW(), NOW()),
(22, 'India', 'World Wide > Asia  > India >', 2, 1, NOW(), NULL, NOW(), NOW()),
(61, 'Japan', 'Japan', 2, 1, NOW(), NULL, NOW(), NOW()),
(262, 'Canada', 'World Wide > Europe > canada >', 7, 1, NOW(), NULL, NOW(), NOW());

-- Level 3: Children of Level 2 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(24, 'Dhaka', 'World Wide > Asia  > Bangladesh > Dhaka >', 21, 1, NOW(), NULL, NOW(), NOW()),
(203, 'Molvibazar', 'World Wide > Asia  > Bangladesh > Molvibazar >', 21, 1, NOW(), NULL, NOW(), NOW()),
(341, 'Chattagram ', 'World Wide > Asia  > Bangladesh > Chattagram  >', 21, 1, NOW(), NULL, NOW(), NOW()),
(23, 'Mumbai', 'World Wide > Asia  > India > Mumbai >', 22, 1, NOW(), NULL, NOW(), NOW()),
(224, 'pune', 'World Wide > Asia  > India > pune >', 22, 1, NOW(), NULL, NOW(), NOW()),
(281, 'New Dellih', 'World Wide > Asia  > India > New Dellih >', 22, 1, NOW(), NULL, NOW(), NOW()),
(62, 'Tokoyo', 'World Wide > Asia  > Japan > Tokoyo >', 61, 1, NOW(), NULL, NOW(), NOW());

-- Level 4: Children of Level 3 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(9, 'Kishoregonj', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj >', 24, 1, NOW(), NULL, NOW(), NOW()),
(25, 'Motijhill', 'World Wide > Asia  > Bangladesh > Dhaka > Motijhill >', 24, 1, NOW(), NULL, NOW(), NOW()),
(41, 'Pabna', 'Pabna Bangladesh', 24, 1, NOW(), NULL, NOW(), NOW()),
(101, 'uttora', 'World Wide > Asia  > Bangladesh > Dhaka > uttora >', 24, 1, NOW(), NULL, NOW(), NOW()),
(142, 'cumilla', 'World Wide > Asia  > Bangladesh > Dhaka > cumilla >', 24, 1, NOW(), NULL, NOW(), NOW()),
(201, 'Narshingdi', 'World Wide > Asia  > Bangladesh > Dhaka > Narshingdi >', 24, 1, NOW(), NULL, NOW(), NOW()),
(324, 'Gazipur', 'World Wide > Asia  > Bangladesh > Dhaka > Gazipur >', 24, 1, NOW(), NULL, NOW(), NOW()),
(861, 'Gulshan', NULL, 24, 1, NOW(), NULL, NOW(), NOW()),
(361, 'fatickchari', 'World Wide > Asia  > Bangladesh > Chattagram  > fatickchari >', 341, 1, NOW(), NULL, NOW(), NOW());

-- Level 5: Children of Level 4 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(10, 'Bhairab', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj > Bhairab >', 9, 1, NOW(), NULL, NOW(), NOW()),
(223, 'Bajetpur', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj > Bajetpur >', 9, 1, NOW(), NULL, NOW(), NOW()),
(261, 'Bajitpur', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj > Bajitpur >', 9, 1, NOW(), NULL, NOW(), NOW()),
(26, 'Arambag', 'World Wide > Asia  > Bangladesh > Dhaka > Motijhill > Arambag >', 25, 1, NOW(), NULL, NOW(), NOW()),
(362, 'Fakirapul', 'World Wide > Asia  > Bangladesh > Dhaka > Motijhill > Fakirapul >', 25, 1, NOW(), NULL, NOW(), NOW()),
(961, 'Stadium Market.', NULL, 25, 1, NOW(), NULL, NOW(), NOW()),
(162, 'Tomsom Bridge', 'World Wide > Asia  > Bangladesh > Dhaka > cumilla > Tomsom Bridge >', 142, 1, NOW(), NULL, NOW(), NOW()),
(222, 'Raipura', 'World Wide > Asia  > Bangladesh > Dhaka > Narshingdi > Raipura >', 201, 1, NOW(), NULL, NOW(), NOW()),
(941, 'sda', NULL, 201, 1, NOW(), NULL, NOW(), NOW()),
(325, 'Kashimpur', 'World Wide > Asia  > Bangladesh > Dhaka > Gazipur > Kashimpur >', 324, 1, NOW(), NULL, NOW(), NOW()),
(326, 'Konabari', 'World Wide > Asia  > Bangladesh > Dhaka > Gazipur > Konabari >', 324, 1, NOW(), NULL, NOW(), NOW()),
(841, 'Salna', NULL, 324, 1, NOW(), NULL, NOW(), NOW());

-- Level 6: Children of Level 5 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(241, 'Jogonnathpur', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj > Bhairab > Jogonnathpur >', 10, 1, NOW(), NULL, NOW(), NOW()),
(242, 'Lukkhmipur', 'World Wide > Asia  > Bangladesh > Dhaka > Kishoregonj > Bhairab > Lukkhmipur >', 10, 1, NOW(), NULL, NOW(), NOW()),
(921, 'Utholia', NULL, 162, 1, NOW(), NULL, NOW(), NOW()),
(202, 'Srerampur', 'World Wide > Asia  > Bangladesh > Dhaka > Narshingdi > Raipura > Srerampur >', 222, 1, NOW(), NULL, NOW(), NOW()),
(881, 'DBL Group', NULL, 325, 1, NOW(), NULL, NOW(), NOW()),
(327, 'DBL ', 'World Wide > Asia  > Bangladesh > Dhaka > Gazipur > Konabari > DBL  >', 326, 1, NOW(), NULL, NOW(), NOW());

-- Level 7: Children of Level 6 entities
INSERT INTO "Geo_Locations" (id, name, full_address, parent_id, is_active, entry_date, created_by, created_at, updated_at) VALUES
(901, 'Sosur Bari', NULL, 202, 1, NOW(), NULL, NOW(), NOW());

